### ISSUE TITLE
add recipe for hibernate dialect update

### ISSUE THREAD

**Issue by iuliiasobolevska** [openrewrite/rewrite-hibernate#44]
## What problem are you trying to solve?
Hibernate 6.2 dropped support for legacy database versions. As a result, legacy code corresponding to those versions was cleaned. One aspect of it is the clean up of `org.hibernate.dialect`s.

## Describe the situation before applying the recipe
```yml
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
```

## Describe the situation after applying the recipe
```yml
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        org.hibernate.dialect.MySQLDialect
```

## Are you interested in [contributing this recipe to OpenRewrite]
This will look smth like:
```yml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.hibernate.MigrateToHibernateProperties6.2
displayName: Migrate to Hibernate 6.2 properties
description: Migrate properties found in `application.properties` and `application.yml` files.
recipeList:
  - org.openrewrite.properties.ChangePropertyValue:
      propertyKey: spring.jpa.database-platform
      newValue: org.hibernate.dialect.MySQLDialect
      oldValue: org.hibernate.dialect.MySQL5Dialect
  - org.openrewrite.properties.ChangePropertyValue:
      propertyKey: spring.jpa.properties.hibernate.dialect
      newValue: org.hibernate.dialect.MySQLDialect
      oldValue: org.hibernate.dialect.MySQL5Dialect
```
but needs to be extended to all removed dialects.
