### ISSUE TITLE
MigrateToHibernate63 does not call MigrateToHibernate62

### ISSUE THREAD

**Issue by grouvig** [openrewrite/rewrite-hibernate#48]
All MigrateToHibernate recipes call recipes to migrate from an ealier version.
MigrateToHibernate65 calls MigrateToHibernate64 wihich calls MigrateToHibernate63.

But MigrateToHibernate63 does not call MigrateToHibernate62.

https://github.com/openrewrite/rewrite-hibernate/blob/main/src/main/resources/META-INF/rewrite/hibernate-6.3.yml :
```
...
recipeList:
  - org.openrewrite.hibernate.MigrateToHypersistenceUtilsHibernate6.2
  - org.openrewrite.hibernate.MigrateToHypersistenceUtilsHibernate6.3
  - org.openrewrite.java.dependencies.UpgradeDependencyVersion:
      groupId: org.hibernate.orm
      artifactId: '*'
      newVersion: 6.3.x
...
```

Expected:
```
...
recipeList:
  - org.openrewrite.hibernate.MigrateToHibernate62
  - org.openrewrite.hibernate.MigrateToHypersistenceUtilsHibernate6.3
  - org.openrewrite.java.dependencies.UpgradeDependencyVersion:
      groupId: org.hibernate.orm
      artifactId: '*'
      newVersion: 6.3.x
...
```
